---
go_version: 1.15.8
go_home_parent_directory: /usr/local
go_path: /root/go
go_file_name: go{{ go_version }}.linux-amd64.tar.gz
go_download_url: 'https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz'
go_clean_install: false
